[package]
name    = "qvault"
version = "0.1.0"
edition = "2021"
description = "QVAULT ($QVLT) — Quantum-Proof Community Token on Solana"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]
name = "qvault"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang  = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl   = { version = "0.31.1", features = ["token", "metadata"] }

[dev-dependencies]
anchor-client = "0.31.1"
tokio = { version = "1", features = ["full"] }
